name: Unit-tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6 # https://github.com/actions/checkout/tags
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v6 # https://github.com/actions/setup-python/tags
        with:
          python-version: "3.14"
      - name: Install dependencies
        run: pip install --root-user-action=ignore -U -r requirements.txt pip
      - name: PyTest
        run: pytest -v --cov=anki_addons_dataset --cov-report=xml --cov-branch
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v8 # https://github.com/SonarSource/sonarqube-scan-action/tags
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
